### ISSUE TITLE
Listing all packages related to missing data from CRAN

### ISSUE THREAD

**Issue by njtierney** [R-miss-tastic/missing-data-taskview#5]
Using the code from this gist: https://gist.github.com/njtierney/9c7f816ad71e3cb4c5a288031585229f

We can search for missing data related packages

**Comment by njtierney** [comment]
Here is the current list of missing data words:

```
mda_words <- c("miss",
               "missing",
               "NA",
               "na",
               "impute",
               "imputed",
               "imputes",
               "imputation",
               "imputations",
               "imputing")
```

**Comment by njtierney** [comment]
```
mda_words <- c("miss",
               "missing",
               "matrix completion",
               "interpolate",
               "interpolated",
               "interpolation",
               "interpolating",
               "matrix complete",
               "matrix completing",
               "NA",
               "na",
               "impute",
               "imputed",
               "imputes",
               "imputation",
               "imputations",
               "imputing")
```

**Comment by tuxette** [comment]
The script is in the repository. The list is attached 
[missing_packages.txt](https://github.com/R-miss-tastic/missing-data-taskview/files/2293149/missing_packages.txt)

Julie: up to package 'heatmaply' (included)
Nick: up to package 'PEMM' (included)
Nath: the rest

**Comment by tuxette** [comment]
Update for me: **reviewed all my packages**. Questions:

- for pla, the imputation method is only described in http://www.drugfuture.com/Pharmacopoeia/EP7/DATA/50300E.PDF which is very unclear for me

**Note**: I skipped almost all packages that have not been updated in the past two years.
